cp_network_aws:
  name: network-f811fd3c-e45e-43b3-b4b5-1f2b21ab5943
  namespace: 7a9da14a-977c-4100-988e-91867007a3b4
  uid: f811fd3c-e45e-43b3-b4b5-1f2b21ab5943

  providerConfigName: 9ecda321-d154-43b8-886d-9eca2f95d3f7

  network:
    region: us-west-1
    name: vpc-f811fd3c-e45e-43b3-b4b5-1f2b21ab5943
    cidrBlock: 10.10.10.0/24
    ngw: single
    subnetPrivate:
    - cidrBlock: 10.10.10.0/28
      az: us-west-1b
    - cidrBlock: 10.10.10.16/28
      az: us-west-1b
    - cidrBlock: 10.10.10.32/28
      az: us-west-1c
    subnetPublic:
    - cidrBlock: 10.10.10.48/28
      az: us-west-1b
    - cidrBlock: 10.10.10.64/28
      az: us-west-1b
    - cidrBlock: 10.10.10.80/28
      az: us-west-1c
    eksName: teste-plk

  tags:
  - key: "Env"
    value: teste-plk
